# Generated by Django 4.0.5 on 2022-07-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreSomeOfOurLatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameH2', models.CharField(max_length=50, verbose_name='EXPLORE SOME OF OUR LATEST')),
                ('img', models.ImageField(upload_to='media', verbose_name='EXPLORE image')),
                ('nameH4', models.CharField(max_length=50, verbose_name='FOR WHOT')),
                ('date', models.CharField(max_length=50, verbose_name='EXPLORE UPDATE DAY')),
                ('seeMore', models.CharField(max_length=50, verbose_name='EXPLORE SEE MORE')),
                ('country', models.CharField(max_length=50, verbose_name='COUNTRY')),
                ('aboutThis', models.CharField(max_length=50, verbose_name='ABOUT EXPLORE')),
            ],
            options={
                'verbose_name': 'ExploreSomeOfOurLatest',
                'verbose_name_plural': 'ExploreSomeOfOurLatests',
            },
        ),
    ]
