# Generated by Django 4.0.5 on 2022-07-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exploresomeofourlatest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreSomeOfOurLatest_Left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameH2', models.CharField(max_length=50, verbose_name='EXPLORE SOME OF OUR LATEST')),
                ('img', models.ImageField(upload_to='media', verbose_name='EXPLORE image')),
            ],
            options={
                'verbose_name': 'ExploreSomeOfOurLatest_Left',
                'verbose_name_plural': 'ExploreSomeOfOurLatests_Left',
            },
        ),
        migrations.RemoveField(
            model_name='exploresomeofourlatest',
            name='img',
        ),
        migrations.RemoveField(
            model_name='exploresomeofourlatest',
            name='nameH2',
        ),
    ]
