# Generated by Django 4.0.5 on 2022-07-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_exploresomeofourlatest_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameH2', models.CharField(max_length=50, verbose_name='Check Out 1')),
                ('nameH2br', models.CharField(max_length=50, verbose_name='Check Out 2')),
                ('aboutThis', models.CharField(max_length=50, verbose_name='ABOUT Check Out')),
                ('aboutImg', models.CharField(max_length=50, verbose_name='ABOUT Check Out Image')),
                ('aboutImgSpan', models.CharField(max_length=50, verbose_name='ABOUT Check Out Image Span')),
                ('img', models.ImageField(upload_to='media', verbose_name='Check Out image')),
            ],
            options={
                'verbose_name': 'CheckOut',
                'verbose_name_plural': 'CheckOuts',
            },
        ),
    ]
