# Generated by Django 4.0.5 on 2022-07-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Base page Footer  image')),
                ('about', models.CharField(max_length=50, verbose_name='ABOUT Base Footer')),
                ('ourLocation', models.CharField(max_length=50, verbose_name='Our Location Base Footer')),
                ('ourLocation1br', models.CharField(max_length=50, verbose_name='Our Location Base Footer')),
                ('ourLocation2br', models.CharField(max_length=50, verbose_name='Our Location Base Footer')),
                ('ourLocation3br', models.CharField(max_length=50, verbose_name='Our Location Base Footer')),
                ('customerCare', models.CharField(max_length=50, verbose_name='Customer Care Base Footer')),
                ('customerCare1rb', models.CharField(max_length=50, verbose_name='Customer Care Base Footer')),
                ('customerCare2br', models.CharField(max_length=50, verbose_name='Customer Care Base Footer')),
                ('customerCare3br', models.CharField(max_length=50, verbose_name='Customer Care Base Footer')),
                ('followUs', models.CharField(max_length=50, verbose_name='Follow Us Base Footer')),
            ],
            options={
                'verbose_name': 'BaseFooter',
                'verbose_name_plural': 'BaseFooters',
            },
        ),
    ]
