# Generated by Django 4.0.5 on 2022-07-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_basefooter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameH2', models.CharField(max_length=50, verbose_name='Explore page 1')),
                ('nameH1', models.CharField(max_length=50, verbose_name='Explore page 2')),
                ('img', models.ImageField(upload_to='media', verbose_name='Explore page image')),
            ],
            options={
                'verbose_name': 'ExplorePage',
                'verbose_name_plural': 'ExplorePages',
            },
        ),
    ]
