# Generated by Django 4.0.5 on 2022-07-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_explorepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameH2', models.CharField(max_length=50, verbose_name='About page 1')),
                ('nameH1', models.CharField(max_length=250, verbose_name='About page 2')),
                ('img', models.ImageField(upload_to='media', verbose_name='About page image')),
            ],
            options={
                'verbose_name': 'AboutPage',
                'verbose_name_plural': 'AboutPages',
            },
        ),
    ]
