# Generated by Django 4.0.5 on 2022-07-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameH2', models.CharField(max_length=250, verbose_name='About page 1')),
                ('nameH1', models.CharField(max_length=250, verbose_name='About page 2')),
                ('img', models.ImageField(upload_to='media', verbose_name='About page image')),
                ('about1', models.CharField(max_length=550, verbose_name='About page 2')),
                ('about2', models.CharField(max_length=550, verbose_name='About page 2')),
            ],
            options={
                'verbose_name': 'AboutUsPage',
                'verbose_name_plural': 'AboutUsPages',
            },
        ),
    ]
