# Generated by Django 4.0.5 on 2022-07-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_aboutuspage_about1_remove_aboutuspage_about2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('profession', models.CharField(max_length=250, verbose_name='Profession')),
                ('about', models.CharField(max_length=250, verbose_name='About')),
                ('img', models.ImageField(upload_to='media', verbose_name='About Team image')),
            ],
            options={
                'verbose_name': 'AboutTeam',
                'verbose_name_plural': 'AboutsTeam',
            },
        ),
    ]
