# Generated by Django 4.0.5 on 2022-07-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aboutteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameH2', models.CharField(max_length=250, verbose_name='Trending name')),
                ('nameH1', models.CharField(max_length=250, verbose_name='About Trending')),
                ('img', models.ImageField(upload_to='media', verbose_name='Trending page image')),
            ],
            options={
                'verbose_name': 'TrendingPage',
                'verbose_name_plural': 'TrendingPages',
            },
        ),
    ]
